services:
  observer-device-count:
    image: rianmachado/observer-device-count:v1
    ports:
      - '8082:8082'
    environment:
      KAFKA_BOOTSTRAP_SERVERS: >
        b-2.xxxxxxxxxxx.amazonaws.com:9092
        b-1.yyyyyyyyyyy.amazonaws.com:9092