services:
  observer-player-device:
    image: rianmachado/observer-player-device:v1
    ports:
      - '8081:8081'
    environment:
      KAFKA_BOOTSTRAP_SERVERS: >
        b-1.supremabrpoker.37y1bv.c3.kafka.us-east-1.amazonaws.com:9094
        b-2.supremabrpoker.37y1bv.c3.kafka.us-east-1.amazonaws.com:9094